name: 'Install Provisioning Profile'
description: 'Install Provisioning Profile'
author: 'Steve Hall'
inputs:
  encoded-profile:        
    description: 'BASE64 encoded provisioning profile'
    required: true
runs:
  using: 'node12'
  main: 'lib/installprovprofile.js'
  post: 'lib/postinstallprovprofile.js'
  post-if: 'success()'
branding:
  icon: 'smartphone'
  color: 'green'
  