name: Release

on: create

jobs:
  release:
    name: Release GitHub Action Install iOS Provisioning Profile
    runs-on: [macOS-latest]
    steps:
      - name: Release GitHub Actions
        uses: technote-space/release-github-actions@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
